### ISSUE TITLE
[FEATURE] Ability to copy contents or download a file

### ISSUE THREAD

**Issue by haxzie** [haxzie/snipp.in#1]
Add options in the dropdown menu of files to copy contents or download the actual file into the system

**Comment by vhawk19** [comment]
Is this still open?

**Comment by haxzie** [comment]
Yes! Would you like to work on it @vhawk19 ? Let me know if you need any help :wink:

**Comment by haxzie** [comment]
The menu options are currently commented out, you can start here.

https://github.com/haxzie/snipp.in/blob/5ba1f37b3a6f7e554f6d1ef2c12d60daa4cf3eba/src/components/FileItem.vue#L35

**Comment by vhawk19** [comment]
Yes, I am certainly keen on trying it out and making it work. I just tried the application out today and really liked it. I am not sure if i would be able to make it work though, largely because of my inexperience with vue. But am going to try hacking on it over the next couple of days.😅

**Comment by FlorianWoelki** [comment]
If you haven't start, I think the [file-saver](https://www.npmjs.com/package/file-saver) dependency is good first try. :)

**Comment by vhawk19** [comment]
Thanks a lot for the suggestion @FlorianWoelki.I started out with it, and was facing some issues with the download part. I was trying to add the functionality without any external dependency using download attribute, Blob API in javascript. Any thoughts on that?
