### ISSUE TITLE
[FEATURE] Right click to create new folder/file

### ISSUE THREAD

**Issue by FlorianWoelki** [haxzie/snipp.in#22]
Hey there,

this is a question or a feature request.
From a UX/UI perspective, it might be useful to let the user right-click in the file explorer to create files/menus. Like in VSCode. Is it useful to create some sort of this feature?

Cheers and happy new year 🎆

**Comment by prikeshsavla** [comment]
You are thinking of adding a context  menu on the sidebar for New file / Folder ?

**Comment by FlorianWoelki** [comment]
I agree with you @prikeshsavla :) We just block the normal right-click and then it will open a context menu when you right-click.

**Comment by haxzie** [comment]
>We just block the normal right-click and then it will open a context menu when you right-click.

@FlorianWoelki that sounds good :raised_hands:

**Comment by FlorianWoelki** [comment]
Beautiful :) If no one else want to work on this, I would tackle this task :)
