### ISSUE TITLE
[FEATURE] Close Other Tabs | Close Tabs to the Left/Right (Right Click on Tab)

### ISSUE THREAD

**Issue by DivyanshBatham** [haxzie/snipp.in#30]
The title is self-explanatory :)

**Comment by DivyanshBatham** [comment]
@haxzie Once I get time, I'll start pushing out PRs here too :)

**Comment by urangurang** [comment]
I also thought it will be good to have this feature.
@DivyanshBatham 
Do you have any update about this feature ?

**Comment by DivyanshBatham** [comment]
@urangurang I'm running super busy, unable to work on this. Would you like to take this up?

**Comment by urangurang** [comment]
Sure, I will get to it this week. 
If you are okay, please assign this issue to me.

**Comment by DivyanshBatham** [comment]
@urangurang Unfortunately, I don't have the permissions to do that.

@haxzie was hospitalized, and is just coming back to work. I'll ask him to assign you the issue.

**Comment by haxzie** [comment]
Thanks for willing to work on this @urangurang! I have assigned the issue to you, drop a comment here anytime if you need any help :)

**Comment by haxzie** [comment]
Implemented in #64
