### ISSUE TITLE
[FEATURE] Persist the open files on refresh or reload

### ISSUE THREAD

**Issue by haxzie** [haxzie/snipp.in#7]
Currently whenever we open snipp.in, it opens the welcome screen. We can store the details of last opened files (file_id and editor_id) in LocalStorage and load them when the app opens up next time. This can also be used to save the recent files list and populate them in the welcome screen.

**Comment by ChoukseyKhushbu** [comment]
@haxzie I would like to work on this issue. Can I take this issue?

**Comment by haxzie** [comment]
Sure, go ahead :+1:
