### ISSUE TITLE
[BUG] Handling empty file/folder renaming

### ISSUE THREAD

**Issue by devblin** [haxzie/snipp.in#74]
**Current behavior:**

- While renaming folder without any name, the folder gets deleted even if there are files inside it.
- While renaming file without any name, the file gets deleted even if there are contents inside it.

**Expected behavior:**

- User should be shown a warning that folder/file renaming can't be empty, and the previous folder/file name should be reapplied if folder/file have contents inside else delete it.

**Comment by devblin** [comment]
If the issue is confirmed, I would like to work on this.

**Comment by haxzie** [comment]
Sure @devblin, go ahead 🙌🏻
