### ISSUE TITLE
Docker Image Building failed 

### ISSUE THREAD

**Issue by cinetube** [haxzie/snipp.in#75]
Docker Image Building failed. Please check the attached screenshot and resolve the issue

![111](https://user-images.githubusercontent.com/23441775/143186922-018db846-de86-4ed8-bc03-2feda0e8f1f8.jpg)

![222](https://user-images.githubusercontent.com/23441775/143186937-654b453a-6da2-449d-9c48-d5a827fc9433.jpg)

**Comment by cinetube** [comment]
@haxzie

**Comment by haxzie** [comment]
Thanks for catching this @cinetube will look into this :raised_hands:

**Comment by MohamedElashri** [comment]
#76 fix the problem.
